# Generated by Django 3.1.7 on 2021-03-25 09:18

from django.db import migrations
import django_resized.forms
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210325_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image_third',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/product/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='somelocationmodel',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [41.26848144933652, 69.22686929378176], 'cursor_style': 'pointer', 'fullscreen_button': True, 'geocoder': True, 'marker_color': 'red', 'navigation_buttons': True, 'placeholder': 'Pick a location on map below', 'readonly': True, 'rotate': True, 'track_location_button': True, 'zoom': 7}),
        ),
    ]
