# Generated by Django 3.1.7 on 2021-03-25 10:09

import ckeditor.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210325_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/home/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image_second',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/home/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='header',
            name='image_third',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, size=[1280, 860], upload_to='uploads/home/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='first_list',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='second_list',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='third_list',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
