# Generated by Django 3.1.7 on 2021-03-27 09:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210325_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='first_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='second_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='third_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
