# Generated by Django 3.1.7 on 2021-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210327_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
