# Generated by Django 3.1.7 on 2021-03-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_productdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(default='product', max_length=100),
        ),
    ]
