# Generated by Django 3.1.7 on 2021-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210327_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
