# Generated by Django 3.1.7 on 2021-03-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210327_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ('title',), 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
    ]
