# Generated by Django 3.1.7 on 2021-03-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210327_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'ordering': ('-created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='date',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
